Advanced numpy operation

Broadcasting in numpy:
    allow the numpy to perform arithmetic operation on array of different shapes. smaller array are automatically expanded to match the shape of larger arrays.
    Rules:
        *Dimensions are aligned from the right.
        *A dimension is compatible if:
             -it matches the other arrays dimension.
             -One of the dimension is 1.     

In [1]:
import numpy as np

In [2]:
#array and scalar broadcasting
arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


In [5]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([1,0,1])
print(matrix + vector)

[[2 2 4]
 [5 5 7]]


Aggregation Functions
 - compute summary statistics for arrays

In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print("Sum", np.sum(arr))
print("Mean", np.mean(arr))
print("Max:", np.max(arr))
print("Min", np.min(arr))
print("Standard Deviation", np.std(arr))
print("Sum along rows", np.sum(arr, axis=1))
print("Sum along columns", np.sum(arr , axis=0))

Sum 21
Mean 3.5
Max: 6
Min 1
Standard Deviation 1.707825127659933
Sum along rows [ 6 15]
Sum along columns [5 7 9]


Boolean indexing and filtering

In [8]:
a = np.array([1,2,3,4,5,6])
evens = a[a%2 ==0]  #filtering
print("Evens",evens)
a[a>3]=0
print("Modified Array:", a)

Evens [2 4 6]
Modified Array: [1 2 3 0 0 0]


In [15]:
#Random number generatiion and setting seeds 
random_array = np.random.rand(3,3)
print("Random array:\n", random_array)

Random array:
 [[0.00706631 0.02306243 0.52477466]
 [0.39986097 0.04666566 0.97375552]
 [0.23277134 0.09060643 0.61838601]]


In [14]:
random_integers = np.random.randint(0,10,size=(2,3))
print("Random integers:\n", random_integers)

Random integers:
 [[5 1 4]
 [0 9 5]]


In [16]:
np.random.seed(42)     #how many the code runs the output will never change
random_array = np.random.rand(3,3)
print("Random array:\n", random_array)
random_integers = np.random.randint(0,10,size=(2,3))
print("Random integers:\n", random_integers)

Random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Random integers:
 [[7 2 5]
 [4 1 7]]


Hands on exercises

In [ ]:
#1)Broadcasting operations 
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,0,-1])
print("Addition\n", matrix + vector)
print("Multiplication\n", matrix * vector)

Addition
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
Multiplication
 [[ 1  0 -3]
 [ 4  0 -6]
 [ 7  0 -9]]


In [ ]:
#2)Generate and filter a random dataset using conditions

#Generate random dataset
dataset = np.random.randint(1,51, size=(5,5))
print("Original datsetL\n", dataset)

#Filter values >25 and replace with 0
dataset[dataset >25 ] =0
print("Modified DatasetL\n", dataset)

#calculate summary stats
print("Sum:", np.sum(dataset))
print("Mean:", np.mean(dataset))
print("Standard deviation:", np.std(dataset))


Original datsetL
 [[44 30 38  2 21]
 [33 12 22 44 25]
 [49 27 42 28 16]
 [15 47 44  3 37]
 [ 7 21  9 39 18]]
Modified DatasetL
 [[ 0  0  0  2 21]
 [ 0 12 22  0 25]
 [ 0  0  0  0 16]
 [15  0  0  3  0]
 [ 7 21  9  0 18]]
Sum: 171
Mean: 6.84
Standard deviation: 8.748394138354763
