Intro to numpy for numerical computing

In [1]:
import numpy as np

create array

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

Using built in function

In [8]:
zeroes = np.zeros((3,3))  #creating a zeroes array
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones((3,3))  #creating ones array
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
range_arr = np.arange(1,10,2) #give range of array
range_arr

array([1, 3, 5, 7, 9])

In [10]:
linspace_arr = np.linspace(0,1,5)  #Interval between numbers
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Manipulating array

In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((3,2))   #change the shape of array
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
expanded = arr[:, np.newaxis]     #add an axis, to increase the dimension of an array
expanded

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Basic operation on array

In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])
a+b   #addition

array([5, 7, 9])

In [ ]:
a*b  #multiplication

array([ 4, 10, 18])

In [ ]:
a/b   #division

array([0.25, 0.4 , 0.5 ])

In [ ]:
arr=np.array([4,16,25])   #mathemathical operation
np.sqrt(arr)         #square root of array

array([2., 4., 5.])

In [ ]:
np.sum(arr)   #sum of array

np.int64(45)

In [ ]:
np.mean(arr)          # mean of array

np.float64(15.0)

In [ ]:
np.max(arr)     #max of array

np.int64(25)

Array indexing , slicing and reshaping

In [30]:
arr = np.array([10,20,30,40,50,60])
arr[2]   #indexing

np.int64(30)

In [31]:
arr[1:4]      #slicing

array([20, 30, 40])

In [32]:
arr[: 3]

array([10, 20, 30])

In [ ]:
reshape_arr  = arr.reshape(3,2)
reshape_arr  #reshaping

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
Hands on exercise

1) Generate Array for basic mathematical operations

In [41]:
c = np.arange(1,6)
d = np.arange(6,11)
print("Add" , c+d)
print("sub" , c-d)
print("Mul" , c*d)
print("Div", c/d)


Add [ 7  9 11 13 15]
sub [-5 -5 -5 -5 -5]
Mul [ 6 14 24 36 50]
Div [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


2) Create a 3*3 matrix and perform operations

In [45]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original matrix\n", matrix)
transpose = matrix.T
print("Transpose matrix\n" ,transpose)

Original matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [46]:
another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Addition:\n", matrix + another_matrix)
print("Multiplication:\n", matrix * another_matrix)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
