LINEAR ALGEBRA FUNDAMENTAL

VECTOR AND MATRICES
vector    eg: [4,7,8]
matrix    eg:[[3,5,7],[9,2,6].[3,4,7]]

MATRIX OPORATION
*ADDITION AND SUBTRACTION  - add and subtract two matrix
*MATRIX MULTIPLICATION     - multiply two matrix a and b together
*SCALAR MULTIPLICATION     -multiply every element 

SPECIAL MATRIX
*IDENTITY MATRIX     - diagonal have one and other are zero in matrix
*ZERO MATRIX         - create zero matrix for given dimension matrix
*DIAGONAL MATRIX     - insert a element in diagonal and others are 0 in matrix

In [2]:
import numpy as np

In [6]:
#create two matrix
a = np.array([[3,6,9],[2,4,6],[5,10,1]])
b = np.array([[4,8,9],[2,5,1],[3,7,1]])
#addition matrix
print("Addition matrix:\n",a+b)
print("Subtraction matrix:\n", a-b)

Addition matrix:
 [[ 7 14 18]
 [ 4  9  7]
 [ 8 17  2]]
Subtraction matrix:
 [[-1 -2  0]
 [ 0 -1  5]
 [ 2  3  0]]


In [8]:
#scalar multiplication
c = 2*a
print("Scalar multiplication:\n",c)

#multiplication matrix
res = np.dot(a,b)
print("Matrix multiplication:\n",res)

Scalar multiplication:
 [[ 6 12 18]
 [ 4  8 12]
 [10 20  2]]
Matrix multiplication:
 [[ 51 117  42]
 [ 34  78  28]
 [ 43  97  56]]


In [9]:
#special matrix
#identity matrix
I = np.eye(2)
print("Identity matrix:\n",I)

#Zero matrix
z = np.zeros((2,3))
print("Zeros matrix:\n",z)

#diagonal matrix
d = np.diag([7,3,44])
print("Diagonal matrix:\n",d)

Identity matrix:
 [[1. 0.]
 [0. 1.]]
Zeros matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
Diagonal matrix:
 [[ 7  0  0]
 [ 0  3  0]
 [ 0  0 44]]


ADVANCED LINEAR ALGEBRA
DETERMINANT
  -calculate only for square matrix
  -det(A) equal to 0 , matrix is singular
  -det(A) not equal to 0, A is invertible
  -det([[a,b],[c,d]]) = ad - bc 
INVERSE MATRIX
  -matrix is invertible only if det A not equal to 0
  -A inverse = 1/det(A)*([[d,-b],[-c,a]])
  -A * A inverse equal to identity matrix

In [11]:
#find determinant 
A = np.array([[2,8],[5,1]])
result = np.linalg.det(A)
print("Determinant of A:\n",result )
#find inverse
res1 = np.linalg.inv(A)
print("Inverse of A matrix:\n", res1)

Determinant of A:
 -37.99999999999999
Inverse of A matrix:
 [[-0.02631579  0.21052632]
 [ 0.13157895 -0.05263158]]


EIGEN VALUES AND EIGEN VECTOR
 -properties of square matrix
 -describe transformation
 -if A.V =LAMBDA.V then V is eigen vertor , LAMBDA is eigen value
EIGEN VALUES
 -indicate the factor of stretching
EIGEN VECTOR
 -point in direction where the matrix transformation stretches
PROPERTIES
 -matrix n has n eigen values and eigen vectors
 -can be real or complex
 -for symmetric matrix, eigen values are always real

In [12]:
eigenvalues, eigenvector = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvector:\n", eigenvector)

Eigenvalues:
 [ 7.84428877 -4.84428877]
Eigenvector:
 [[ 0.80748079 -0.75985955]
 [ 0.58989386  0.65008727]]


MATRIX DECOMPOSITION
  - to break matrix into small segment and analyze or solve the problem
SINGULAR VALUE DECOMPOSITION(SVD)
  - SVD decomposes a matrix A into 3 matrix A = U* SIGMA* VPOWERT
  - U : left singular vector(orthogonal matrix)
  -SIGMA : diagonal matrix of singular values (non negative)
  -VPOWERT: right singular vector

In [13]:
U, S , VT = np.linalg.svd(A)
print("U:\n",U)
print("Singular values:\n",S)
print("VT:\n",VT)

U:
 [[-0.93788501 -0.34694625]
 [-0.34694625  0.93788501]]
Singular values:
 [8.64052275 4.39788206]
VT:
 [[-0.41785681 -0.9085129 ]
 [ 0.9085129  -0.41785681]]


In [17]:
#RECONSTRUCT
sigma = np.zeros((2,2))
np.fill_diagonal(sigma,S)
recons = U @ sigma @ VT
print(recons)

[[2. 8.]
 [5. 1.]]
